### ISSUE TITLE
local variable 'corruption_value' referenced before assignment

### ISSUE THREAD

**Issue by niansa** [Calendis/CalCorrupt#1]
Opend file: /tmp/0022 - Super Mario 64 DS (Europe) (En,Fr,De,Es,It).nds

Corruption stacking is OFF. Resetting byte data to original.

Corrupting every 2 bytes.

Starting at 1 and ending at .

Chance of corruption: 40.

Corruption value: .

No end byte. Going all the way.

Corrupting file!

Exception in Tkinter callback

Traceback (most recent call last):

  File "/usr/lib/python3.6/tkinter/__init__.py", line 1702, in __call__

    return self.func(*args)

  File "./calcorrupt.py", line 113, in corrupt_file

    byte_data[b] = (byte_data[b] + int(corruption_value))%255

UnboundLocalError: local variable 'corruption_value' referenced before assignment

**Comment by Calendis** [comment]
This is caused because you didn't set a corruption value. I'll make it notify the user if this happens instead of just failing. Thanks for the report.

EDIT: I've added error handling. To make this absolutely clear I'll make a change to the UI too.
