### ISSUE TITLE
doesn't work in european locale

### ISSUE THREAD

**Issue by toomykins** [Calendis/CalCorrupt#2]
Hey my dude your application works great, messing around with it right now.
Had to restart my computer though, Had my locale set to dutch, which means every dot is a comma and every comma a dot, your code couldn't read the GUI input and gave an error, changing my locale fixed it.
thanks for the cool little program.

**Comment by Calendis** [comment]
Oh wow, I hadn't even considered this! Anyway, I THINK it should be fixed now with a simple replacement of commas with periods before converting to float. I got lazy and didn't want to switch my locale to test it. Thanks for the input!

I'll close the issue for now, but if it still doesn't work let me know
