### ISSUE TITLE
Corrupts with Increment even with a value of 0

### ISSUE THREAD

**Issue by anonymousAwesome** [Calendis/CalCorrupt#4]
If the byte value is 255, the script converts it to 0 (255 modulo 255 is 0) instead of leaving it at 255. This can corrupt the file even when the corruption value is zero.

I tested a version where I changed every instance of % 255 to % 256 and that seemed to fix the problem.

**Comment by Calendis** [comment]
thanks for reporting (and fixing, lol). Sometimes life gets in the way but I got around to fixing it
